"""LaTeX tables and in-text numbers of the Electronics manuscript, computed from the saved CSVs.

Writes paper/electronics/tables/*.tex (tabular blocks only; captions live in main.tex) and
paper/electronics/tables/numbers.md (every number quoted in the text, with its source).
Points = 100 x metric. Category means first (5 draws), then means over categories. Paired
differences: per category mean over N, 95% bootstrap CI over categories (10,000 resamples, seed 0),
W/T/L = categories won/tied/lost with a 0.5-point margin.

Usage: uv run make_paper_tables.py
"""

from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path("paper/electronics/tables")
OUT.mkdir(parents=True, exist_ok=True)
R = Path("output/server_run")
NS = [1, 2, 4, 5]
DEV = ("mvtec_AD", "VisA")
BENCH = ["mvtec_AD", "VisA", "mvtec_loco_AD", "AutoVI", "btad", "GoodsAD"]
BNAME = {"mvtec_AD": "MVTec~AD", "VisA": "VisA", "mvtec_loco_AD": "MVTec~LOCO", "AutoVI": "AutoVI",
         "btad": "BTAD", "GoodsAD": "GoodsAD"}

notes = ["# Numbers quoted in the manuscript (generated by `make_paper_tables.py`)", ""]


def note(s):
    notes.append(s)


def load(f):
    d = pd.read_csv(f)
    d["bench"] = d.dataset.str.split("/").str[0]
    return d


def cat_mean(d, metric, n=None):
    if n is not None:
        d = d[d.n_train == n]
    return d.groupby("dataset")[metric].mean() * 100


def paired(a, b):
    x = (a - b.reindex(a.index)).dropna()
    g = np.random.default_rng(0)  # one seeded generator per comparison: same CI wherever it is quoted
    bs = [g.choice(x.values, len(x)).mean() for _ in range(10000)]
    return x.mean(), np.percentile(bs, 2.5), np.percentile(bs, 97.5), (x > 0.5).sum(), (x.abs() <= 0.5).sum(), (x < -0.5).sum()


def fmt_pair(p, ci=True):
    s = f"${p[0]:+.2f}$"
    if ci:
        s += f" [${p[1]:+.2f}$, ${p[2]:+.2f}$]"
    return s


def wtl(p):
    return f"{p[3]}/{p[4]}/{p[5]}"


def over_n(da, db, metric, ns=NS, cats=None):
    """Per category mean over N of each method, then paired difference."""
    a = pd.concat([cat_mean(da, metric, n) for n in ns], axis=1).mean(axis=1)
    b = pd.concat([cat_mean(db, metric, n) for n in ns], axis=1).mean(axis=1)
    if cats is not None:
        a = a[a.index.isin(cats)]
    return paired(a, b)


def f1(v):
    """One decimal, but 100 instead of 100.0 (as in the authors' published tables)."""
    s = f"{v:.1f}"
    return "100" if s == "100.0" else s


def bold_rows(rows, cols):
    """Bold the best value per column among rows (list of lists of floats); ties as printed."""
    best = [f1(max(r[c] for r in rows)) for c in cols]
    return [[("\\textbf{" + f1(v) + "}" if (c in cols and f1(v) == best[cols.index(c)]) else f1(v))
             for c, v in enumerate(r)] for r in rows]


def summary_cols(d, metric, n, cats_all):
    """Per-benchmark means, then development, held-out and all-category means."""
    cm = cat_mean(d, metric, n)
    cm = cm[cm.index.isin(cats_all)]
    vals = [cm[cm.index.str.startswith(b + "/")].mean() for b in BENCH]
    dev = cm[cm.index.str.startswith(DEV)]
    ext = cm[~cm.index.str.startswith(DEV)]
    return vals + [dev.mean(), ext.mean(), cm.mean()]


# ---------------------------------------------------------------- data
L = load(R / "l_square.csv")
G, A = L[L.method == "galad"], L[L.method == "adino"]
O = load("output/adino_official.csv")
cats = sorted(L.dataset.unique())
ext = [c for c in cats if not c.startswith(DEV)]
note(f"- Categories: {len(cats)} ({len(cats) - len(ext)} development, {len(ext)} held-out)")

# ---------------------------------------------------------------- Table: benchmarks
rows = []
for b in BENCH:
    cb = [c for c in cats if c.startswith(b + "/")]
    lab = [np.load(R / "scores/l_square" / c.replace("/", "__") / "N1_s0_galad.npz")["labels"] for c in cb]
    nn, na = sum((y == 0).sum() for y in lab), sum((y == 1).sum() for y in lab)
    role = "Development" if b in DEV else "Held-out"
    rows.append(f"{BNAME[b]} & {len(cb)} & {nn} & {na} & {100 * na / (nn + na):.1f} & {role} \\\\")
(OUT / "benchmarks.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Table: main image AP
lines = []
for n in NS:
    vals = [summary_cols(O, "img_ap", n, cats), summary_cols(A, "img_ap", n, cats), summary_cols(G, "img_ap", n, cats)]
    vals = bold_rows(vals, list(range(len(vals[0]))))
    names = ["AnomalyDINO (official)", "AnomalyDINO (DINOv3-L)", "GaLAD"]
    for i, (nm, v) in enumerate(zip(names, vals)):
        first = f"\\multirow{{3}}{{*}}{{{n}}}" if i == 0 else ""
        lines.append(f"{first} & {nm} & " + " & ".join(v) + " \\\\")
    lines.append("\\midrule" if n != NS[-1] else "")
(OUT / "main_ap.tex").write_text("\n".join(l for l in lines if l) + "\n", encoding="utf-8")

# image AUROC (appendix), same layout
lines = []
for n in NS:
    vals = [summary_cols(O, "img_auroc", n, cats), summary_cols(A, "img_auroc", n, cats), summary_cols(G, "img_auroc", n, cats)]
    vals = bold_rows(vals, list(range(len(vals[0]))))
    names = ["AnomalyDINO (official)", "AnomalyDINO (DINOv3-L)", "GaLAD"]
    for i, (nm, v) in enumerate(zip(names, vals)):
        first = f"\\multirow{{3}}{{*}}{{{n}}}" if i == 0 else ""
        lines.append(f"{first} & {nm} & " + " & ".join(v) + " \\\\")
    lines.append("\\midrule" if n != NS[-1] else "")
(OUT / "main_auroc.tex").write_text("\n".join(l for l in lines if l) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Table: paired differences
rows = []
for name, ref in (("AnomalyDINO (DINOv3-L)", A), ("AnomalyDINO (official)", O)):
    p_all, p_ext = over_n(G, ref, "img_ap"), over_n(G, ref, "img_ap", cats=ext)
    rows.append(f"{name} & {fmt_pair(p_all)} & {wtl(p_all)} & {fmt_pair(p_ext)} & {wtl(p_ext)} \\\\")
    note(f"- AP, GaLAD − {name}, mean over N: {len(cats)} cat. {fmt_pair(p_all)} ({wtl(p_all)}); {len(ext)} held-out {fmt_pair(p_ext)} ({wtl(p_ext)})")
    for n in NS:
        pn = paired(cat_mean(G, "img_ap", n), cat_mean(ref, "img_ap", n))
        pe = paired(cat_mean(G, "img_ap", n)[ext], cat_mean(ref, "img_ap", n))
        note(f"  - N={n}: all {fmt_pair(pn)} ({wtl(pn)}); held-out {fmt_pair(pe)} ({wtl(pe)})")
(OUT / "paired.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
p = over_n(G, A, "img_auroc")
note(f"- AUROC, GaLAD − AnomalyDINO (DINOv3-L), all: {fmt_pair(p)}")
diff_cat = pd.concat([cat_mean(G, "img_ap", n) - cat_mean(A, "img_ap", n) for n in NS], axis=1).mean(axis=1)
diff_cat.to_csv(OUT / "per_category_diff.csv", header=["diff_ap"])
for b in BENCH:
    note(f"- {b}: GaLAD − AnomalyDINO (DINOv3-L) AP {diff_cat[diff_cat.index.str.startswith(b + '/')].mean():+.2f}")

# ---------------------------------------------------------------- Table: same-representation control
pc = pd.read_csv("output/pixel_check.csv")
K = pc[(pc.method == "knn_galad") & (pc.post == "own")].copy()
lines = []
for n in (2, 5):
    ga, gk, gd = cat_mean(G, "img_ap", n), cat_mean(K, "img_ap", n), cat_mean(A, "img_ap", n)
    pa, pk, pd_ = cat_mean(G, "aupro_30", n), cat_mean(K, "aupro_std", n), cat_mean(A, "aupro_30", n)
    rows = [[gd.mean(), pd_.mean()], [gk.mean(), pk.mean()], [ga.mean(), pa.mean()]]
    rows = bold_rows(rows, [0, 1])
    names = ["AnomalyDINO (DINOv3-L)", "1-NN on GaLAD features", "GaLAD"]
    for i, (nm, v) in enumerate(zip(names, rows)):
        first = f"\\multirow{{3}}{{*}}{{{n}}}" if i == 0 else ""
        lines.append(f"{first} & {nm} & {v[0]} & {v[1]} \\\\")
    if n == 2:
        lines.append("\\midrule")
    q1, q2 = paired(ga, gk), paired(pa, pk)
    note(f"- Control N={n}: GaLAD − 1-NN AP {fmt_pair(q1)} ({wtl(q1)}); AU-PRO {fmt_pair(q2)}; "
         f"1-NN − AnomalyDINO AP {gk.mean() - gd.mean():+.2f}")
(OUT / "control.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

# localization numbers (AU-PRO at two FPR limits) for the text
for n in NS:
    for m, lab in (("aupro_30", "0.3"), ("aupro_05", "0.05")):
        q = paired(cat_mean(G, m, n), cat_mean(A, m, n))
        note(f"- AU-PRO@{lab} N={n}: GaLAD {cat_mean(G, m, n).mean():.1f}, AnomalyDINO (DINOv3-L) "
             f"{cat_mean(A, m, n).mean():.1f}, diff {fmt_pair(q)}")
for n in NS:
    note(f"- Pixel (appendix line) N={n}: pixel AUROC {cat_mean(G, 'pix_auroc', n).mean():.1f} / "
         f"{cat_mean(A, 'pix_auroc', n).mean():.1f}; pixel AP {cat_mean(G, 'pix_ap', n).mean():.1f} / "
         f"{cat_mean(A, 'pix_ap', n).mean():.1f}")

# ---------------------------------------------------------------- Table: ablation (development)
g = pd.read_csv("output/tune/gauss_screen.csv")
g = g[g.dataset.str.startswith(DEV) & g.n_train.isin([1, 2]) & g.seed.isin([0, 1, 2])]
g["bench"] = g.dataset.str.split("/").str[0]


def dev_ap(variant):
    x = g[g.variant == variant].groupby(["bench", "dataset", "n_train"]).img_ap.mean() * 100
    assert x.groupby("bench").size().to_dict() == {"VisA": 24, "mvtec_AD": 30}, variant
    return x.groupby(["bench", "n_train"]).mean().groupby("bench").mean().mean()


abl = [("3", "none", "k3"), ("12", "none", "k12s0"), ("12", "$\\kappa=500$", "k12s500"),
       ("12", "$\\kappa=2000$", "k12s2000"), ("12", "$\\kappa=8000$", "k12s8000"),
       ("12", "shared ($\\kappa\\to\\infty$)", "k12sinf"), ("3", "$\\kappa=2000$", "k3s2000"),
       ("6", "$\\kappa=2000$", "k6s2000"), ("24", "$\\kappa=2000$", "k24s2000")]
rows = []
for k, s, v in abl:
    a, c = dev_ap(f"{v}|maha|raw"), dev_ap(f"{v}|chi2|raw")
    final = v == "k12s2000"
    bf = (lambda x: "\\textbf{" + x + "}") if final else (lambda x: x)
    rows.append(" & ".join([bf(k), bf(s), bf(f1(a)), bf(f1(c))]) + " \\\\")
    note(f"- Ablation {v}: Mahalanobis {a:.2f}, chi2 tail {c:.2f}")
(OUT / "ablation.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Table: backbones and cost
rows = []
for tag, name in (("b", "ViT-B/16"), ("l", "ViT-L/16"), ("h", "ViT-H+/16")):
    D = load(R / f"{tag}_square.csv")
    full = D.groupby("dataset").size()
    D = D[D.dataset.isin(full[full == 40].index)]
    if D.dataset.nunique() != len(cats):
        continue
    dg, da = D[D.method == "galad"], D[D.method == "adino"]
    ap = [cat_mean(dg, "img_ap").mean(), cat_mean(da, "img_ap").mean()]
    pr = [cat_mean(dg, "aupro_30").mean(), cat_mean(da, "aupro_30").mean()]
    q = over_n(dg, da, "img_ap")
    bb = pd.read_csv(R / f"bench_{tag}.csv")
    bg = bb[bb.method == "galad"]
    fw = bb.forward_ms.mean()
    fit5 = bg[bg.n_train == 5].fit_s.mean()
    sc = bg.score_ms_fp32.mean()
    st = bg.state_mib.mean()
    rows.append(f"{name} & {f1(ap[0])} & {f1(ap[1])} & ${q[0]:+.1f}$ & {f1(pr[0])} & {f1(pr[1])} & {fw:.0f} & {fit5:.0f} & {sc:.1f} & {st:.1f} \\\\")
    note(f"- Backbone {name}: AP {ap[0]:.1f}/{ap[1]:.1f} diff {fmt_pair(q)}; AU-PRO {pr[0]:.1f}/{pr[1]:.1f}; "
         f"forward {fw:.1f} ms; fit N=5 {fit5:.1f} s; scoring fp32 {sc:.2f} ms (fp64 {bg.score_ms.mean():.2f}); state {st:.2f} MiB")
    for n in (1, 2, 5):
        note(f"  - {name} N={n}: GaLAD fit {bg[bg.n_train == n].fit_s.mean():.1f} s; AnomalyDINO bank "
             f"{bb[(bb.method == 'adino') & (bb.n_train == n)].state_mib.mean():.1f} MiB, scoring "
             f"{bb[(bb.method == 'adino') & (bb.n_train == n)].score_ms.mean():.2f} ms")
(OUT / "backbones.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Appendix: per-category AP
lines = []
for b in BENCH:
    cb = [c for c in cats if c.startswith(b + "/")]
    for i, c in enumerate(cb):
        v = [pd.concat([cat_mean(d, "img_ap", n) for n in NS], axis=1).mean(axis=1)[c] for d in (O, A, G)]
        best = f1(max(v))
        v = ["\\textbf{" + f1(x) + "}" if f1(x) == best else f1(x) for x in v]
        first = f"\\multirow{{{len(cb)}}}{{*}}{{{BNAME[b]}}}" if i == 0 else ""
        name = c.split("/")[1].replace("_", "\\_")
        lines.append(f"{first} & {name} & " + " & ".join(v) + " \\\\")
    if b != BENCH[-1]:
        lines.append("\\midrule")
(OUT / "per_category.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Prespecified endpoint (19 held-out categories)
ext19 = [c for c in ext if c != "AutoVI/pipe_staple"]
for name, ref in (("AnomalyDINO (DINOv3-L)", A), ("AnomalyDINO (official)", O)):
    q = over_n(G, ref, "img_ap", cats=ext19)
    note(f"- Prespecified {len(ext19)} held-out, GaLAD − {name}: {fmt_pair(q)} ({wtl(q)})")
rows = []
for name, cs in ((f"Held-out, prespecified ({len(ext19)})", ext19), (f"Held-out, complete ({len(ext)})", ext),
                 (f"All ({len(cats)})", None)):
    cells = [over_n(G, ref, "img_ap", cats=cs) for ref in (A, O)]
    rows.append(f"{name} & " + " & ".join(f"{fmt_pair(c)} & {wtl(c)}" for c in cells) + " \\\\")
(OUT / "paired.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
for n in NS:
    od = cat_mean(O, "img_auroc", n)
    gd = cat_mean(G, "img_auroc", n)
    dv = [c for c in cats if c.startswith(DEV)]
    note(f"- AUROC dev N={n}: GaLAD − official {gd[dv].mean() - od[dv].mean():+.2f}; "
         f"held-out AP AnomalyDINO (DINOv3-L) {cat_mean(A, 'img_ap', n)[ext].mean():.1f} vs official {cat_mean(O, 'img_ap', n)[ext].mean():.1f}")
gg = pd.read_csv("output/tune/gauss_screen.csv")
gg = gg[gg.dataset.str.startswith(DEV) & gg.n_train.isin([1, 2]) & gg.seed.isin([0, 1, 2]) & (gg.variant == "k3|nll|raw")]
gg["bench"] = gg.dataset.str.split("/").str[0]
note(f"- Ablation anchor, earlier GaLAD (K=3, no shrinkage, likelihood score): "
     f"{(gg.groupby(['bench', 'dataset', 'n_train']).img_ap.mean() * 100).groupby(['bench', 'n_train']).mean().groupby('bench').mean().mean():.2f}")

# ---------------------------------------------------------------- Appendix: draws and defect size
piv = L.pivot_table(index=["dataset", "n_train", "seed"], columns="method", values="img_ap") * 100
per_seed = (piv.galad - piv.adino).groupby(["seed", "dataset"]).mean()
all_s = per_seed.groupby("seed").mean()
ext_s = per_seed[per_seed.index.get_level_values("dataset").isin(ext)].groupby("seed").mean()
note(f"- Per draw, AP diff vs AnomalyDINO (DINOv3-L): all {all_s.min():+.2f} to {all_s.max():+.2f}; "
     f"held-out {ext_s.min():+.2f} to {ext_s.max():+.2f}")
AREA = Path("output/defect_area.csv")
if not AREA.exists():
    import galad_train_all as GT
    rows_a = []
    for c in cats:
        _, info = GT.load_dataset(c)
        fr = [(m > 0).mean() for e in info if e["label"] == 1 and (m := GT.load_mask(e)) is not None and (m > 0).any()]
        rows_a.append((c, np.median(fr) * 100 if fr else np.nan))
    pd.DataFrame(rows_a, columns=["dataset", "median_area_pct"]).to_csv(AREA, index=False)
area = pd.read_csv(AREA, index_col=0).median_area_pct.reindex(cats).dropna()
q = area.quantile([1 / 3, 2 / 3]).values
for lab, sel in (("small", area <= q[0]), ("medium", (area > q[0]) & (area <= q[1])), ("large", area > q[1])):
    pr = paired(diff_cat[area[sel].index], 0 * diff_cat[area[sel].index])
    note(f"- Defect size {lab} third ({sel.sum()} cat., area <= {area[sel].max():.1f}%): {fmt_pair(pr)}")

# ---------------------------------------------------------------- Appendix: localization
lines = []
for n in NS:
    v = [cat_mean(O, "aupro_std", n).mean(), cat_mean(A, "aupro_30", n).mean(), cat_mean(G, "aupro_30", n).mean(),
         cat_mean(A, "aupro_05", n).mean(), cat_mean(G, "aupro_05", n).mean()]
    b03, b05 = f1(max(v[:3])), f1(max(v[3:]))
    cells = ["\\textbf{" + f1(x) + "}" if f1(x) == (b03 if i < 3 else b05) else f1(x) for i, x in enumerate(v)]
    lines.append(f"{n} & " + " & ".join(cells) + " \\\\")
    q = paired(cat_mean(G, "aupro_30", n), cat_mean(O, "aupro_std", n))
    note(f"- AU-PRO@0.3 N={n}: GaLAD − AnomalyDINO (official) {fmt_pair(q)} ({wtl(q)})")
(OUT / "localization.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Appendix: leave one benchmark out
rows = []
for b in BENCH:
    keep = [c for c in cats if not c.startswith(b + "/")]
    pa = paired(diff_cat[keep], 0 * diff_cat[keep])
    if b in DEV:
        pe = "---"
    else:
        ke = [c for c in ext if not c.startswith(b + "/")]
        pe = fmt_pair(paired(diff_cat[ke], 0 * diff_cat[ke]))
    rows.append(f"{BNAME[b]} & {fmt_pair(pa)} & {pe} \\\\")
by_b = diff_cat.groupby(lambda c: c.split("/")[0]).mean()
note(f"- Benchmark-balanced mean difference: 6 benchmarks {by_b.mean():+.2f}; 4 held-out {by_b[BENCH[2:]].mean():+.2f}")
(OUT / "lobo.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

(OUT / "numbers.md").write_text("\n".join(notes) + "\n", encoding="utf-8")
print(f"wrote {len(list(OUT.glob('*.tex')))} tables and numbers.md to {OUT}")
